MESOS_MASTER=lxcc01 # should be the leader
MESOS_MASTER_IP_PORT=$(vm ip $MESOS_MASTER):5050

export  MESOS_MASTER \
        MESOS_MASTER_IP_PORT

echo MESOS_MASTER=$MESOS_MASTER
echo MESOS_MASTER_IP_PORT=$MESOS_MASTER_IP_PORT
